on:
  push:
    branches: 
    - master 
name: Bump version, build and release npm package
jobs:
  build-npm:
    name: Build npm package
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: bump
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor # gets overriden by PR label
      - uses: actions/checkout@v1
      - run: npm i
      - run: npm test
      - run: npm version ${{ steps.bump.outputs.version }}
      - run: npm publish
