on:
  push:
    branches: 
    - master 

name: Bump version, build and release npm package
jobs:
  build-npm:
    name: Build npm package
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    steps:
      - uses: actions/checkout@v1
      - name: Automated Github Action Version Bump
        uses: rimonhanna/gh-action-bump-version@master
      - run: npm i
      - run: npm test
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
