on:
  push:
    branches: 
    - feature/github-actions

name: build and release npm package
jobs:
  build-npm:
    name: Build npm package
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test form
      - name: Build
        run: yarn build form
      - name: Version Bump
        uses: rimonhanna/gh-action-bump-version@master
        env:
          PACKAGEJSON_DIR: dist/libs/form
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/libs/form/package.json
